version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: .venv/bin/python3 -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    volumes:
      - ./app:/home/app/app
    env_file:
      - .env.dev