version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    environment:
      - DEBUG=true
    ports:
      - 8000:8000
    volumes:
      - ./app:/home/app/app
      - ./app/db/migrations:/home/app/app/db/migrations
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: